### ISSUE TITLE
What is the license of this project?

### ISSUE THREAD

**Issue by tomxp411** [crankery/emulate#1]
Hello, Dave. I hope you're well.

I've recently been playing around with Altair emulation, and I found a front panel project I want to marry to some code on the PC. 

The front panel is the one from altairduino.com. I've already written a new Arduino sketch to give me direct access to the LEDs and switches. The next step is to get an emulator on the PC talking to it. 

I'd love to flesh out the Altair8800 code to work with my Altair front panel, but without a license, I don't know what the Copyright status of your code is. 

Could you add a license to the project, or at least reply here, to let me know whether it's okay to redistribute your emulator? 

Thanks
-Tom

**Comment by crankery** [comment]
Hey Tom,

Not a problem. Threw an MIT license on it, have fun.

**Comment by crankery** [comment]
Huh. I guess I should go fix all the source files and remove the `obj\Debug` garbage that got in there somehow.

**Comment by tomxp411** [comment]
Yeah, I always have to go through and set up ignore filters when setting up a new project in source control. I usually ignore all the obj and bin directories. That reminds me. I need to install a git client...
